blueprint:
  name: "NordPool: termostaat"
  description: Määra kaks temperatuuri termostaadi jaoks
  source_url: https://github.com/anexosholding/smartserver-blueprints/blob/main/blueprints/automation/nordpool-termostaat.yaml
  domain: automation
  input:
    price_entity:
      name: NordPool sensor
      selector:
        entity:
          multiple: false
          device_class: monetary
    hours:
      name: Tundide arv
      description: Mitmel kõige odavamal tunnil soovid termostaati kõrgemaks seadistada?
      selector:
        number:
          min: 1
          max: 23
          step: 1
          unit_of_measurement: h
    temp_low:
      name: Alandatud temperatuur
      description: Soovitud temperatuur kõrgema börsihinna korral
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: °C
    temp_high:
      name: Kõrgem temperatuur
      description: Soovitud temperatuur madalama börsihinna korral
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: °C
    thermostat:
      name: Termostaadid
      selector:
        entity:
          multiple: true
          domain: climate

variables:
  price: !input price_entity
  hours: !input hours
  price_now: "{{ states(price) }}"
  _price_limit: "{{state_attr(price, 'today')|sort}}"
  price_limit: "{{_price_limit[:hours]}}"
  high: !input temp_high
  low: !input temp_low

trigger:
  - platform: time_pattern
    minutes: 0
    seconds: 15 # viivitus täistunnist

action:
  - if:
      - condition: template
        value_template: "{{price_now <= price_limit|max}}"
    then:
      - service: climate.set_temperature
        alias: "Elekter on odav, seadistan termostaadid ümber"
        data:
          entity_id: !input thermostat
          temperature: "{{ high | float }}"
    else:
      - service: climate.set_temperature
        alias: "Elekter on kallis, seadistan termostaadid ümber"
        data:
          entity_id: !input thermostat
          temperature: "{{ low | float }}"
