blueprint:
  name: "NordPool: keskmine hind"
  description: Lülitab seadme sisse, kui börsihind on alla ööpäeva keskmise, samuti välja, kui üle keskmise
  source_url: https://github.com/anexosholding/smartserver-blueprints/blob/main/blueprints/automation/nordpool-keskmine-hind.yaml
  domain: automation
  input:
    price_entity:
      name: NordPool sensor
      selector:
        entity:
          multiple: false
          device_class: monetary
    light:
      name: Valgustid
      selector:
        entity:
          multiple: true
          domain: light
    switch:
      name: Lülitid
      selector:
        entity:
          multiple: true
          domain: switch

variables:
  _price: !input price_entity
  price_now: "{{ states(_price) }}"
  price_avg: "{{state_attr(_price, 'average')}}"

trigger:
  - platform: time_pattern
    minutes: 00
    seconds: 15 # väike viivitus täistunnist

action:
  - service: >
      {% if price_now <= price_avg %}
        light.turn_on
      {% else %}
        light.turn_off
      {% endif %}
    target:
      entity_id: !input light
    alias: "Hind on alla keskmise, lülitan tuled ümber"
  - service: >
      {% if price_now <= price_avg %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    alias: "Hind on alla keskmise, lülitan lülitid ümber"
    target:
      entity_id: !input switch
