blueprint:
  name: Madalaima börsihinnaga tunnid
  description: Vali järjestikkuste tundide arv, mil on kõige odavam elektrit börsihinnaga tarbida.
  source_url: https://github.com/antsmartti/smartserver-blueprints/blob/main/blueprints/automation/nordpool-madalaimad-tunnid.yaml
  domain: automation
  input:
    number_of_hours:
      name: Tundide arv
      description: Vajalikud tunnid, mil on plaanis rohkem elektrit tarbida
      selector:
        number:
          min: 1
          max: 24
          mode: slider
          step: 1
    electricity_price_sensor:
      name: Börsihinna sensor
      description: NordPooli sensor, mis annab tänase päeva börsihinnad. 
      selector:
        entity:
          domain: sensor

trigger:
  platform: time_pattern
  hours: "/1" # Trigger every hour

action:
  - variables:
      number_of_hours: !input number_of_hours
      electricity_prices: # Assuming the electricity price sensor stores the prices for the next 24 hours in a list attribute
        "{{ state_attr(input.electricity_price_sensor, 'tomorrow') }}"

  - choose: # Check if we have enough prices for the next 24 hours
      - conditions:
          - "{{ electricity_prices | length >= 24 }}"
        sequence:
          - service: notify.notify # Notify the selected hours
            data:
              message: >-
                {% set selected_hours = [] %}
                {% for start_hour in range(24 - number_of_hours + 1) %}
                  {% set consecutive_prices = electricity_prices[start_hour:start_hour+number_of_hours]|sum %}
                  {% if selected_hours|length == 0 or consecutive_prices < selected_hours[0].total_price %}
                    {% set selected_hours = [{'start_hour': start_hour, 'total_price': consecutive_prices}] %}
                  {% endif %}
                {% endfor %}
                Madalaima hinnaga {{ number_of_hours }} tundi algab kell {{ selected_hours[0].start_hour }}.
